spring:
  application:
    name: ms-openapi-gateway
  cloud:
    kubernetes:
      reload:
        enabled: true
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  swagger-ui:
    path: /
    config-url: /swagger-config.json